CREATE TABLE "Person" (
	"ID"		INTEGER DEFAULT 0 PRIMARY KEY,
	"FirstName"	TEXT DEFAULT '' NOT NULL,
	"LastName"	TEXT DEFAULT '' NOT NULL,
	"Phone1"	TEXT DEFAULT '' NOT NULL,
	"Phone2"	TEXT DEFAULT '' NOT NULL,

	"isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,	
);

CREATE TABLE "Address" (
    "ID"			INTEGER DEFAULT 0 PRIMARY KEY,
    "fk_PersonID" 	INTEGER DEFAULT 0 REFERENCES Person(ID)NOT NULL 
    "Address1"	TEXT DEFAULT '' NOT NULL,
	"Address2"	TEXT DEFAULT '' NOT NULL,
	"Address3"	TEXT DEFAULT '' NOT NULL,
	"City"		TEXT DEFAULT '' NOT NULL,
	"Province"	TEXT DEFAULT '' NOT NULL,
	"Country"	TEXT DEFAULT '' NOT NULL,
	"PostalCode"	TEXT DEFAULT '' NOT NULL,

    "isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,

);

CREATE TABLE "Donation" (
	"ID"			INTEGER DEFAULT 0 PRIMARY KEY,
	"fk_PersonID"	INTEGER DEFAULT 0 REFERENCES Person(ID) NOT NULL, --foreign key
	"Amount"	REAL DEFAULT 0 NOT NULL,
	"Date"		TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL

	"isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,
);


CREATE TABLE "ReceiptPrinted" (
    "ID"			INTEGER DEFAULT 0 PRIMARY KEY,
    "fk_PersonID" 	INTEGER DEFAULT 0 REFERENCES Person(ID)NOT NULL,
    "Amount" 	REAL DEFAULT 0 NOT NULL ,
    "Year" 		INTEGER DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "isPrinted" INTEGER DEFAULT 0 NOT NULL,

    "isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,
);