CREATE TABLE "Donation" (
	"ID"			INTEGER DEFAULT 0 PRIMARY KEY,
	"fk_PersonID"	INTEGER DEFAULT 0 REFERENCES Person(ID) NOT NULL, --foreign key
	"Amount"	REAL DEFAULT 0 NOT NULL,
	"Date"		TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL

	"isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,
);