CREATE TABLE "Person" (
	"ID"		INTEGER DEFAULT 0 PRIMARY KEY,
	"FirstName"	TEXT DEFAULT '' NOT NULL,
	"LastName"	TEXT DEFAULT '' NOT NULL,
	"Phone1"	TEXT DEFAULT '' NOT NULL,
	"Phone2"	TEXT DEFAULT '' NOT NULL,

	"isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,	
);