CREATE TABLE "ReceiptPrinted" (
    "ID"			INTEGER DEFAULT 0 PRIMARY KEY,
    "fk_PersonID" 	INTEGER DEFAULT 0 REFERENCES Person(ID)NOT NULL,
    "Amount" 	REAL DEFAULT 0 NOT NULL ,
    "Year" 		INTEGER DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "isPrinted" INTEGER DEFAULT 0 NOT NULL,

    "isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"CreatedAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"DeletedAt" TEXT DEFAULT '' NOT NULL,
);