CREATE TABLE "person" (
	"id"		INTEGER PRIMARY KEY,
	"firstName"	TEXT DEFAULT '' NOT NULL,
	"lastName"	TEXT DEFAULT '' NOT NULL,
	"phone1"	TEXT DEFAULT '' NOT NULL,
	"phone2"	TEXT DEFAULT '' NOT NULL,

	"isDeleted"	INTEGER DEFAULT 0 NOT NULL,
	"createdAt" TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deletedAt" TEXT DEFAULT '' NOT NULL	
);