CREATE TABLE "receipt_records" (
    "id"			INTEGER PRIMARY KEY,
    "fk_PersonId" 	INTEGER DEFAULT 0 REFERENCES Person(ID)NOT NULL,
    "amount" 		REAL DEFAULT 0 NOT NULL ,
    "datePrinted"	TEXT DEFAULT '' NOT NULL,
    "isPrinted" 	INTEGER DEFAULT 0 NOT NULL,

	"isDeleted"		INTEGER DEFAULT 0 NOT NULL,
	"createdAt" 	TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"deletedAt" 	TEXT DEFAULT '' NOT NULL
);